### PR TITLE
[RVV 0.7.1] Use `Debug` build in self-hosted runner

### PR DESCRIPTION
**Pull request by imkiva**
as title

### CODE REVIEW

**Comment by imkiva** [comment]
Ohhhhh it is working now!!!!!!!!!!!!

image

**Comment by ChunyuLiao** [comment]
@ AinsleySnow, fix error. 👆

**Comment by ChunyuLiao** [comment]
@AinsleySnow fix error. 👆

**Comment by AinsleySnow** [comment]
> @AinsleySnow fix error. 👆

The root of the error is that in RVV 0.7.1 there is no vmxr instructions (e.g. vm1r, vm2r) at all, but I mistakenly thought they are available in RVV 0.7.1 and used them in vamo tests. Vmxr instructions are used in the test cases to move result of vamo to the v8 register for returning.

But I go through the whole RVV 0.7.1 Spec and find there seems no counterpart of vmxr, and even worse it appears that no instruction can directly copy value in a vector register to another. I have come out of a workaround, that is to emit a vadd instruction (or vsub, vor, whatever), and let v8 be its destination, vamo result be one of its operand and zero be the other operand.

I am not sure about the workaround. Asking for comments... @imkiva @ChunyuLiao

**Comment by AinsleySnow** [comment]
> > @AinsleySnow fix error. 👆
> 
> The root of the error is that in RVV 0.7.1 there is no vmxr instructions (e.g. vm1r, vm2r) at all, but I mistakenly thought they are available in RVV 0.7.1 and used them in vamo tests. Vmxr instructions are used in the test cases to move result of vamo to the v8 register for returning.
> 
> But I go through the whole RVV 0.7.1 Spec and find there seems no equivalence of vmxr, and even worse it appears that no instruction can directly copy value in a vector register to another. I have come out of a workaround, that is to emit a vadd instruction (or vsub, vor, whatever), and let v8 be its destination, vamo result be one of its operand and zero be the other operand.
> 
> I am not sure about the workaround. Asking for comments... @imkiva @ChunyuLiao

Ah, I see, I can use vm.v.v. Thank you anyway.

**Pull request merged**
