### PR TITLE
[RVV 0.7.1] MC support

### PR DESCRIPTION
**Pull request by imkiva**
According to #3, this PR tries to merge [MC support implemented here](https://github.com/Terapines/llvm-project) into this repo. Cherry-pick is performed and the changes are merged to resolve conflicts, which are mainly caused by the following upstream changes since Apr 14:

- https://github.com/ruyisdk/llvm-project/commit/1f3008733231517d7aed2493403e7fa130028538
- https://github.com/ruyisdk/llvm-project/commit/bbf96e68b181dfc148277a2c8d241901fe24f598
- https://reviews.llvm.org/D150238
- https://reviews.llvm.org/D148733
- https://reviews.llvm.org/D150753

### CODE REVIEW

**Comment by imkiva** [comment]
Progress report:

- Fixed all conflicts and test failure caused by upstream changes, but the parser for _Register List_ in `Zcmp` extension seems broken. I am seeking for help 😭 

The stack trace of `llvm-mc llvm/test/MC/RISCV/rv32zcmp-valid.s -triple=riscv32 -mattr=zcmp -riscv-no-aliases -show-encoding`

```
llvm-mc: /home/kiva/llvm-project/llvm/include/llvm/MC/MCAsmMacro.h:116: int64_t llvm::AsmToken::getIntVal() const: Assertion `Kind == Integer && "This token isn't an integer!"' failed.              
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.                                                                                           
Stack dump:                                      
0.      Program arguments: /home/kiva/buildhost/bin/llvm-mc /home/kiva/llvm-project/llvm/test/MC/RISCV/rv32zcmp-valid.s -triple=riscv32 -mattr=zcmp -riscv-no-aliases -show-encoding                  
 #0 0x00007f846f992118 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/kiva/llvm-project/llvm/lib/Support/Unix/Signals.inc:602:22                                                           
 #1 0x00007f846f9924f7 PrintStackTraceSignalHandler(void*) /home/kiva/llvm-project/llvm/lib/Support/Unix/Signals.inc:675:1                                                                            
 #2 0x00007f846f98fbbb llvm::sys::RunSignalHandlers() /home/kiva/llvm-project/llvm/lib/Support/Signals.cpp:104:20                                                                                     
 #3 0x00007f846f991a31 SignalHandler(int) /home/kiva/llvm-project/llvm/lib/Support/Unix/Signals.inc:413:1                                                                                             
 #4 0x00007f846f081520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)                                   
 #5 0x00007f846f0d5a7c pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x96a7c)                      
 #6 0x00007f846f081476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)                           
 #7 0x00007f846f0677f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)                             
 #8 0x00007f846f06771b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)                                   
 #9 0x00007f846f078e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)                                   
#10 0x00007f84701c7ef9 llvm::AsmToken::getIntVal() const /home/kiva/llvm-project/llvm/include/llvm/MC/MCAsmMacro.h:117:31                                                                             
#11 0x00007f84701b6be7 (anonymous namespace)::RISCVAsmParser::parseZcmpSpimm(llvm::SmallVectorImpl<std::unique_ptr<llvm::MCParsedAsmOperand, std::default_delete<llvm::MCParsedAsmOperand>>>&) /home/kiva/llvm-project/llvm/lib/Target/RISCV/AsmParser/RISCVAsmParser.cpp:2572:58                        
#12 0x00007f84701ae1f3 (anonymous namespace)::RISCVAsmParser::tryCustomParseOperand(llvm::SmallVectorImpl<std::unique_ptr<llvm::MCParsedAsmOperand, std::default_delete<llvm::MCParsedAsmOperand>>>&, unsigned int) /home/kiva/buildhost/lib/Target/RISCV/RISCVGenAsmMatcher.inc:12552:35                
#13 0x00007f84701ae486 (anonymous namespace)::RISCVAsmParser::MatchOperandParserImpl(llvm::SmallVectorImpl<std::unique_ptr<llvm::MCParsedAsmOperand, std::default_delete<llvm::MCParsedAsmOperand>>>&, llvm::StringRef, bool) /home/kiva/buildhost/lib/Target/RISCV/RISCVGenAsmMatcher.inc:12603:47      
#14 0x00007f84701b6d4f (anonymous namespace)::RISCVAsmParser::parseOperand(llvm::SmallVectorImpl<std::unique_ptr<llvm::MCParsedAsmOperand, std::default_delete<llvm::MCParsedAsmOperand>>>&, llvm::StringRef) /home/kiva/llvm-project/llvm/lib/Target/RISCV/AsmParser/RISCVAsmParser.cpp:2591:29         
#15 0x00007f84701b7011 (anonymous namespace)::RISCVAsmParser::ParseInstruction(llvm::ParseInstructionInfo&, llvm::StringRef, llvm::SMLoc, llvm::SmallVectorImpl<std::unique_ptr<llvm::MCParsedAsmOperand, std::default_delete<llvm::MCParsedAsmOperand>>>&) /home/kiva/llvm-project/llvm/lib/Target/RISCV/AsmParser/RISCVAsmParser.cpp:2642:3                                                               
#16 0x00007f84701c8cd6 llvm::MCTargetAsmParser::ParseInstruction(llvm::ParseInstructionInfo&, llvm::StringRef, llvm::AsmToken, llvm::SmallVectorImpl<std::unique_ptr<llvm::MCParsedAsmOperand, std::default_delete<llvm::MCParsedAsmOperand>>>&) /home/kiva/llvm-project/llvm/include/llvm/MC/MCParser/MCTargetAsmParser.h:445:3                                                                            
#17 0x00007f8470063a94 (anonymous namespace)::AsmParser::parseAndMatchAndEmitTargetInstruction((anonymous namespace)::ParseStatementInfo&, llvm::StringRef, llvm::AsmToken, llvm::SMLoc) /home/kiva/llvm-project/llvm/lib/MC/MCParser/AsmParser.cpp:2319:58                                              
#18 0x00007f847006394d (anonymous namespace)::AsmParser::parseStatement((anonymous namespace)::ParseStatementInfo&, llvm::MCAsmParserSemaCallback*) /home/kiva/llvm-project/llvm/lib/MC/MCParser/AsmParser.cpp:2309:47                                 
#19 0x00007f847005d933 (anonymous namespace)::AsmParser::Run(bool, bool) /home/kiva/llvm-project/llvm/lib/MC/MCParser/AsmParser.cpp:1001:33                                                           
#20 0x00005629621cc68a AssembleInput(char const*, llvm::Target const*, llvm::SourceMgr&, llvm::MCContext&, llvm::MCStreamer&, llvm::MCAsmInfo&, llvm::MCSubtargetInfo&, llvm::MCInstrInfo&, llvm::MCTargetOptions const&) /home/kiva/llvm-project/llvm/tools/llvm-mc/llvm-mc.cpp:344:45                  
#21 0x00005629621ce1c8 main /home/kiva/llvm-project/llvm/tools/llvm-mc/llvm-mc.cpp:585:24          
#22 0x00007f846f068d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)                                   
#23 0x00007f846f068e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)                 
#24 0x00005629621cbb95 _start (/home/kiva/buildhost/bin/llvm-mc+0x22b95)                   
```

Or if the full log of `ninja check-llvm` will be useful: 
[tmux-history-2-1-1-20230808T165416.log](https://github.com/ruyisdk/llvm-project/files/12289313/tmux-history-2-1-1-20230808T165416.log)

**Comment by imkiva** [comment]
> Can you give a failure case for that problem so that we can locate the problem faster?

Running `llvm-mc` with these files should give a repro:

- `rv32zcmp-invalid.s`
- `rv32zcmp-valid.s`
- `rv64zcmp-invalid.s`
- `rv64zcmp-valid.s`

Like, `llvm-mc llvm/test/MC/RISCV/rv32zcmp-valid.s -triple=riscv32 -mattr=zcmp -riscv-no-aliases -show-encoding`

**Comment by Xinlong-Wu** [comment]
when there is only `DefaultAsmParserVariant` in `AssemblyParserVariants` the `OperandMatchTable` should be 



that's correct.

But when we add 2 `ParserVariants` like `list<AsmParserVariant> AssemblyParserVariants = [DefaultAsmParserVariant, RVV0p71AsmParserVariant];`, the code generator will generate item for each variants. Use `call` Inst as example:

when  `list<AsmParserVariant> AssemblyParserVariants = [DefaultAsmParserVariant];`, `OperandMatchTable` will be like
image

if we add another variant like `list<AsmParserVariant> AssemblyParserVariants = [DefaultAsmParserVariant, RVV0p71AsmParserVariant];`, it will be:
image

Thus the problem in this issue should be `{ 2007 /* cm.pop */, 1 /* 0 */, MCK_Rlist, AMFBS_HasStdExtZcmp },` was not be generate twice.

**Comment by imkiva** [comment]
Finally, we reached the root cause: 

- The register list in the arg string is declared as `{$rlist}`, but curly brackets are used for variant selection.
- In `ArgMatcherEmitter.cpp`, function `MatchableInfo::initialize` calls `CodeGenInstruction::FlattenAsmStringVariants` with the current asm parser variant id and the asm string, to choose the correct operand format by variant id.
- In our case, `{$rlist}` is treated as a variant selection, with `$rlist` being the operand for `DefaultAsmParserVariant`. That's why there's no `rlist` generated in the `OperandMatchTable` for the second variant.

**Pull request merged**
