### PR TITLE
[LLVM][XTHeadVector] Implement intrinsics for vand/vor/vxor.

### PR DESCRIPTION
**Pull request by AinsleySnow**
As title. This one is very similar to #48 !

### CODE REVIEW

**Review by imkiva — APPROVED** [review]
LGTM. tql 🚀

**Comment by AinsleySnow** [comment]
Thank you!😀

**Comment by ChunyuLiao** [comment]
please help rebase.

**Comment by AinsleySnow** [comment]
> please help rebase.

Rebased. Thank you!

**Pull request merged**
