### PR TITLE
[LLVM][XTHeadVector] Implement intrinsic for unit-stride segment loads and stores.

### PR DESCRIPTION
**Pull request by AinsleySnow**
This PR implements intrinsic for unit-stride segment loads and stores.

In the first commit ([087b9d3](https://github.com/ruyisdk/llvm-project/commit/087b9d3da1a24de09e376c2b15741a2c9614b1ec)) I renamed previously defined search tables to make them match the T-Head suggested naming schema.

Other commits are similar to those in previous PRs.

### CODE REVIEW

**Comment by AinsleySnow** [comment]
I found two problems when writing test cases for the vsseg intrinsic. The first one is that llc will complain about register type in PseudoTH_VMV<n>R_V.

If we try to compile the following code with `llc -verify-machineinstrs -mattr=+xtheadvector -mtriple=riscv64`,

```LLVM IR
declare void @llvm.riscv.th.vsseg2b.mask.nxv16i8.nxv16i8(
  <vscale x 16 x i8>, <vscale x 16 x i8>,
  <vscale x 16 x i8>*,
  <vscale x 16 x i1>,
  i32);

define void @intrinsic_vsseg2b_mask_v_nxv16i8_nxv16i8(<vscale x 16 x i8> %0, <vscale x 16 x i8>* %1, <vscale x 16 x i1> %2, i32 %3) nounwind {
entry:
  call void @llvm.riscv.th.vsseg2b.mask.nxv16i8.nxv16i8(
    <vscale x 16 x i8> %0, <vscale x 16 x i8> %0,
    <vscale x 16 x i8>* %1,
    <vscale x 16 x i1> %2,
    i32 %3)
  ret void
}
```

llc will report the following errors:

```
*** Bad machine code: Illegal physical register for instruction ***
- function:    intrinsic_vsseg2b_mask_v_nxv16i8_nxv16i8
- basic block: %bb.0 entry (0x559c523babb8)
- instruction: $v10m2 = PseudoTH_VMV2R_V $v8m2
- operand 0:   $v10m2
$v10m2 is not a VR register.

*** Bad machine code: Illegal physical register for instruction ***
- function:    intrinsic_vsseg2b_mask_v_nxv16i8_nxv16i8
- basic block: %bb.0 entry (0x559c523babb8)
- instruction: $v10m2 = PseudoTH_VMV2R_V $v8m2
- operand 1:   $v8m2
$v8m2 is not a VR register.
```

These errors can be easily fixed by modifying the `VR`s below to VRM2, VRM4, etc:

```LLVM TableGen
    def PseudoTH_VMV1R_V : XVPseudoWholeMove<TH_VMV_V_V, V_M1, VR>;
    def PseudoTH_VMV2R_V : XVPseudoWholeMove<TH_VMV_V_V, V_M1, VR>;
    def PseudoTH_VMV4R_V : XVPseudoWholeMove<TH_VMV_V_V, V_M1, VR>;
    def PseudoTH_VMV8R_V : XVPseudoWholeMove<TH_VMV_V_V, V_M1, VR>;
```

**Comment by AinsleySnow** [comment]
However, the second one is somewhat tricky. After correct the type above, I found PseudoTH_VMV\<n\>R_V is not correctly expanded. For the snippet above, llc's output is:

```Assembly
	th.vmv.v.v	v10, v8
	th.vsetvli	zero, a1, e8, m2, d1
	th.vsseg2b.v	v8, (a0), v0.t
	ret
```

Obviously the pseudo instruction didn't being correctly expanded, and it seemed that emitXWholeMove didn't work. 

It is because emitXWholeMove will be called in the FinalizeISel pass, and the VMV pseudos are generated by the ExpandPostRAPseudos pass, which will run **after** the former one. Therefore we can see in the assembly that vmv2r simply being replaced with vmv.v.v without any other changes.

Technically we can directly call XWholeMove in the ExpandPostRAPseudos pass, but I'm not sure about this change. Currently I just set all vector parameters of the intrinsic to `undef` to avoid the PostRA pass generating vmv.v.v instructions.

**Comment by imkiva** [comment]
> 
> These errors can be easily fixed by modifying the `VR`s below to VRM2, VRM4, etc:
> 
> ```llvm
>     def PseudoTH_VMV1R_V : XVPseudoWholeMove<TH_VMV_V_V, V_M1, VR>;
>     def PseudoTH_VMV2R_V : XVPseudoWholeMove<TH_VMV_V_V, V_M1, VR>;
>     def PseudoTH_VMV4R_V : XVPseudoWholeMove<TH_VMV_V_V, V_M1, VR>;
>     def PseudoTH_VMV8R_V : XVPseudoWholeMove<TH_VMV_V_V, V_M1, VR>;
> ```

Oh looks like `NREGS` in `vmv<n>r` should be interpreted as `LMUL` in RVV 0.7? I am quite unsure of these cases where `n != 1` to be honest. But what I want to say is: the VRClass here (`VR`, `VRM2`, etc.) is just for well-typedness, and the lowering behavior is also fixed with the `n`, as you can see in the `emitXWholeMove` function.

So if changing the VRClass helps the problem, let's change it.

**Comment by imkiva** [comment]
> Technically we can directly call `XWholeMove` in the `ExpandPostRAPseudos` pass, but I'm not sure about this change. Currently I just set all vector parameters of the intrinsic to `undef` to avoid the PostRA pass generating `vmv.v.v` instructions.

It is okay to extract common code from `emitXWholeMove` to some places that are available across passes. See `copyPhysReg`/`storeRegToStackSlot`/`loadRegFromStackSlot` in `RISCVInstrInfo.cpp` for usages where some common lowering logic is called from other passes.

**Review by imkiva — APPROVED** [review]
Ok. LGTM then.

**Pull request merged**
